openapi: 3.0.1
info:
  title: Biblioteca Comunitária API
  description: API RESTful para gestão de livros e empréstimos.
  version: "1.0.0"

servers:
  - url: http://localhost:5000/api
    description: Servidor local de desenvolvimento

paths:
  /books:
    post:
      summary: Criar um novo livro
      tags: [Books]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BookCreateCommand'
      responses:
        '201':
          description: Livro criado com sucesso
        '400':
          description: Requisição inválida

    get:
      summary: Listar todos os livros
      tags: [Books]
      responses:
        '200':
          description: Lista de livros
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/BookReadModel'

  /books/{id}:
    get:
      summary: Obter livro por ID
      tags: [Books]
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Livro encontrado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BookReadModel'
        '404':
          description: Livro não encontrado

  /loans:
    get:
      summary: Listar todos os empréstimos
      tags: [Loans]
      responses:
        '200':
          description: Lista de empréstimos
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/LoanReadModel'

  /loans/{id}:
    get:
      summary: Obter empréstimo por ID
      tags: [Loans]
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Empréstimo encontrado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LoanReadModel'
        '404':
          description: Empréstimo não encontrado

  /loans/request:
    post:
      summary: Solicitar um novo empréstimo
      tags: [Loans]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RequestLoanCommand'
      responses:
        '201':
          description: Empréstimo criado com sucesso
        '400':
          description: Erro de regra de domínio (ex: livro indisponível)

  /loans/return:
    post:
      summary: Devolver um empréstimo
      tags: [Loans]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ReturnLoanCommand'
      responses:
        '204':
          description: Devolução realizada com sucesso
        '400':
          description: Erro de regra de domínio (ex: empréstimo já devolvido)

components:
  schemas:
    BookCreateCommand:
      type: object
      required: [titulo, autor, anoPublicacao, quantidadeDisponivel]
      properties:
        titulo:
          type: string
        autor:
          type: string
        anoPublicacao:
          type: integer
        quantidadeDisponivel:
          type: integer

    BookReadModel:
      type: object
      properties:
        id:
          type: string
          format: uuid
        titulo:
          type: string
        autor:
          type: string
        anoPublicacao:
          type: integer
        quantidadeDisponivel:
          type: integer

    RequestLoanCommand:
      type: object
      required: [livroId]
      properties:
        livroId:
          type: string
          format: uuid

    ReturnLoanCommand:
      type: object
      required: [id]
      properties:
        id:
          type: string
          format: uuid

    LoanReadModel:
      type: object
      properties:
        id:
          type: string
          format: uuid
        livroId:
          type: string
          format: uuid
        dataEmprestimo:
          type: string
          format: date-time
        dataDevolucao:
          type: string
          format: date-time
          nullable: true
        status:
          type: string
          enum: [Ativo, Devolvido]